<main>
   <div class="observer" style="top: 70px;"></div>
   <section data-v-7452ac7a="" class="static-page">
      <header data-v-7452ac7a="">
         <h2 data-v-7452ac7a="">Gizlilik İlkesi</h2>
      </header>
      <article data-v-7452ac7a="" class="app-container">
         <p><strong>Gizlilik İlkesi<br>
            1. GIZLILIK</strong>
         </p>
         <p><strong>Kisisel bilgilerinizi korumaya söz veriyoruz. Bu Gizlilik Ilkesini, Siz Hizmetlerimizi kullanirken Bizim hangi bilgileri derledigimiz, bu bilgileri neden derledigimiz ve derlenen bu bilgileri ne sekilde kullanacagimiz konusunda sizi bilgilendirmek için olusturduk.</strong></p>
         <p><strong>Bu Gizlilik Ilkesi için, Siz ve www.MeritKing.com&nbsp;( Global Money Services Ltd) olarak, Kullanim Sartlari ve Kosullari'nda belirtilen ilgili Grup sirketleri ile birlikte, Grup arasinda ('MeritKing,'biz', 'bizi, bize' veya 'bizim') anlasmaya varilmistir.</strong></p>
         <p><strong>Bu Gizlilik Ilkesi'nde düzenli araliklarla degisiklikler yapabiliriz, bu degisiklikleri tarafiniza degistirilmis sartlari Platformlarimizda ilan ederek yapacagiz. Bu Gizlilik Ilkesi sayfamizi düzenli olarak ziyaret etmenizi öneririz.</strong></p>
         <p><strong>2. TOPLANAN BILGILER</strong></p>
         <p><strong>Kisinin adi ve soyadi, dogum tarihi, kredi karti bilgileri, ev veya diger fiziksel adresleri, e-posta adresi, telefon numarasi ve diger irtibat bilgileri dahil olmak ancak bunlarla sinirli olmamak kaydiyla, bir bireyin kimligini tespit etmek için kullanilabilecek bilgileri Kisisel Bilgiler ('Kisisel Bilgiler') olarak dikkate aliriz. Web sitemizi kullanirken, bir hesaba kayit yaptirirken veya Hizmetlerimizi kullanabilmeniz için sizden Kisisel Bilgilerinizi vermeniz istenebilir. Derledigimiz Kisisel Bilgiler sunlari içerebilir: irtibat bilgileri (telefon numarasi dahil), sevkiyat bilgileri, fatura bilgileri, islem geçmisi, web sitesi kullanim tercihleri ve Hizmetlere iliskin geribildirimler. Bu bilgileri, Amerika'da veya zaman zaman baska yerlerde bulunan sunucularimiz araciligiyla muhafaza ederiz. Ek olarak, Hizmetlerle karsilikli iletisime girdiginizde sunucularimiz, asagidakileri içeren belirli idari ve islem bilgilerini kaydeden, size özel bir faaliyet günlügü tutacaktir: kaynak IP adresi, erisim zamani, erisim tarihi, ziyaret edilen web sayfa(lar)i, kullanilan dil, yazilim ariza raporlari ve kullanilan tarayici tipi. Bu bilgiler, Hizmetlerin saglanmasi ve kalitesi açisindan zorunludur. Hizmetlere iliskin Kisisel Bilgilerinizi, sizin bilginiz olmadan derlemeyiz.</strong></p>
         <p><strong>3. VERI TOPLAMA VE ISLEME ARAÇLARI</strong></p>
         <p><strong>Yukarida belirtilen belirli bilgileri ve hakkinizdaki Kisisel Bilgileri, bu bilgileri Hizmetler üzerinden sagladiginizda veya bizimle yaptiginiz diger iletisimler ve etkilesimler sirasinda otomatik olarak kaydedebiliriz. Kisisel Bilgileri ayrica, çevrimiçi satici ve hizmet saglayicilardan ve üçüncü taraf saticilardan yasal biçimde elde edilen müsteri listelerinden de alabiliriz. Ek olarak, teknik destek saglamak, çevrimiçi islemlerinizi yürütmek ve Hesabinizi muhafaza etmek için üçüncü taraf hizmet saglayicilarinin hizmetlerini de devreye sokabiliriz. Bu satici, hizmet saglayici ve üçüncü taraf e-ticaret hizmetlerine verdiginiz tüm bilgilere erisime sahip olacak ve Kisisel Bilgileri, asagida yer alan Gizlilik Ilkesi'nde belirlenen sekilde kullanacagiz. Bu bilgiler, bu Gizlilik Ilkesi'ne uygun olarak, sadece Grup disindaki üçüncü taraflara açiklanacaktir. Üçüncü taraf hizmet saglayicilar ve çevrimiçi saticilarla yapacagimiz düzenlemelerde gizliliginizi korumak için gerekli tedbirleri almaktayiz.</strong></p>
         <p><strong>4. BILGI KULLANIMI</strong></p>
         <p><strong>Sizden aldigimiz Kisisel Bilgileri, Hizmetlerimizi sunmak, müsteri destegi saglamak, gerekli güvenlik ve kimlik bilgileri dogrulama kontrollerini üstlenmek, tüm çevrimiçi islemlerinizi yürütmek, üçüncü taraf promosyonlariniza katiliminiza yardimci olmak, belirli is gerekliliklerini karsilamak ve Hizmetlerin saglanmasina iliskin diger tüm amaçlari yerine getirmek için kullaniriz. Bu şekilde kişisel bilgilerinizi diğer partnerlerimizle (ve bu partnerin bilgi transferi yaptığı her şirket buna dahil olmak üzere) paylaşabiliriz. Kişisel bilgilerinizi; (a) ürünlerimiz ve hizmetlerimiz ile ilgili promosyonlar ve bilgiler ve/veya (b) partnerlerimizin ürünleri ve hizmetleri ile ilgili promosyonlar ve bilgiler sunmak üzere kullanabiliriz. Kisisel Bilgileriniz tarafimizca size promosyon teklifleri ve ürün ve hizmetlerimize iliskin bilgileri sunmak ve daha iyi bir ürün ve hizmet serisi ve daha iyi müsteri hizmetleri saglayabilmek için de kullanilabilir. Eğer e-mail adresiniz, sitemizde hesabı olan diğer bir üyemizin e-mail listesindeki kişiler listesinde kayıtlıysa, bu e-mail adresinin sistemimizde kayıtlı olduğunun diğer üyeye bildirilmesini kabul edersiniz. Zaman zaman sizden anketler veya yarismalar yoluyla bilgiler de isteyebiliriz. Bu anket veya yarismalara katilim tamamen istege baglidir ve bu nedenle, bu bilgileri açiklama veya açiklamama seçenegine sahipsiniz. Istenilen bilgiler, irtibat bilgilerini (örn. isim, iletisim adresi ve telefon numarasi) ve demografik bilgileri (örn. posta kodu veya yas) içerebilir. Bizden alacaginiz herhangi bir yarisma ödül veya kazanimi kabul etmeniz, adiniz veya benzer bilgilerinizin, yasalara uygun sekilde herhangi bir ilave tazminat hakki dogmadan reklam ve promosyon amaçli kullanilmasini onaylamaniz anlamina gelir. Promosyon bilgilerini almayi tercih ediyorsaniz, (e-mail adresiniz ve telefon numaraniz dahil olmak üzere) Kisisel Bilgilerinizi, size diger oyun ürünlerini (örn. poker, casino, bahis, tavla ve bingo hizmetleri) ve dikkatle seçtigimiz üçüncü taraflarin ürün ve hizmetlerini de içeren ürünlerimiz, hizmetlerimiz ve promosyonlarimiza iliskin bilgiler saglamak için de kullanabiliriz.</strong></p>
         <p><strong>5. KAPSAM DISI AÇIKLAMALAR</strong></p>
         <p><strong>Kisisel Bilgilerinizi, yasalar gerektirdigi takdirde veya söz konusu eylemin sunlari yapmak için gerekli olduguna iyi niyetle inandigimiz durumlarda açiklayabiliriz: (1) Bizim üzerimizde, sitelerimiz veya Hizmetlerimizden herhangi biri üzerinde veya büyük ölçüde benzer bir yasal yükümlülük altinda oldugumuz durumlarda yürütülen herhangi bir yasal sürece uyum göstermek; (2) hak veya mülklerimizi korumak ve savunmak; veya (3) Hizmetin kullanicilarinin kisisel güvenligini korumak üzere hareket etmek. Tamamen kendi inisiyatifimizde olmak kaydiyla, bizi, Grubu veya baska bir Hizmet kullanicisini, oyun hilesi veya ödeme sahtekârligi dahil olmak ancak bunlarla sinirli olmamak kaydiyla herhangi bir sekilde aldattiginiz veya dolandirmaya tesebbüs ettiginiz saptanirsa veya çalinti kredi karti veya herhangi diger hileli faaliyet (örn. her türlü geri ödeme veya diger sekillerde ödeme iadesi) veya yasak islem (örn. para aklama) dahil olmak üzere hileli ödeme yaptiginizdan süphe duyarsak, (kimlik bilgilerinizle birlikte) bu bilgileri diger çevrimiçi oyun siteleri, bankalar, kredi karti sirketleri ve uygun araci kurumlarla paylasma hakkini sakli tutariz. (4) Oyun bağımlılığını önlemek amacıyla yapılan çalışmalar için çeşitli oyun ve oyuncu verileri anonim olarak toplanarak ilgili araştırma kurumlarına aktarılabilir.</strong></p>
         <p><strong>6. ERISIM</strong></p>
         <p><strong>Bu seçenegin kullanilabilir kilindigi Site veya Hizmetlerimizde veya bizden alacaginiz bir e-posta mesajinda 'almama' seçenegini seçerek veya herhangi bir zamanda bir e-posta mesaji göndererek herhangi bir promosyon bildirimini 'almamaya' karar verebilirsiniz. Talep edildigi takdirde, (a) Bu degisiklikler için makul olarak talep edebilecegimiz kanitlari saglamaniz kaydiyla, bize verdiginiz tüm bilgileri güncelleyecegiz, veya (b) gelecekte pazarlama amaçli kullanimini engellemek için tüm bilgileri isaretleyecegiz. Süpheye mahal vermemek için, bu Gizlilik Ilkesindeki hiçbir sey, yasalar tarafindan zorunlu kilindiginda Kisisel Bilgilerinizi alikoymamizi engelleyemez.</strong></p>
      </article>
   </section>
</main>